analysis: low_T_table

paths:
  tf_root: /Applications/Thermal-FIST-1.5.2

params:
  Tmin: 0.005
  Tmax: 0.005
  dT: 0.005
  muBmin: -0.800
  muBmax: 0.800
  dmuB: 0.025
  muQmin: -0.800
  muQmax: 0.800
  dmuQ: 0.025
  muSmin: -0.800
  muSmax: 0.800
  dmuS: 0.025
  model_type: 0
  particle_list: "/Users/jordi/Box/Research/papers/2309.01737/PDG2021Plus/hadron-lists/PDG2021Plus/for_Thermal-FIST/PDG2021Plus-1.0_list.dat"
  decays_list: "/Users/jordi/Box/Research/papers/2309.01737/PDG2021Plus/hadron-lists/PDG2021Plus/for_Thermal-FIST/PDG2021Plus-1.0_full_decays.dat"
  outdir: ./output

runtime:
  workers: 8